# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Lin
email: hello@kevinl.info
description: >
  I teach Computer Science at Berkeley. 
logo: "/assets/images/me.jpg"
baseurl: ""
url: "http://kevinl.info"
paginate: 10

name: 'Kevin Lin'
bio: >
  Berkeley CS + CogSci 2018. I design websites for Berkeley Diversity. Teaching CS is my passion.
author_image: "/assets/images/me.jpg"
twitter_username:
github_username:  kevinlin1

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-redirect-from
